---
name: Fake-SMTP-Server

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: docker buildx build --platform linux/amd64,linux/arm64/v8 --tag ghcr.io/principiamentis/fake-smtp-server:${IMAGE_VERSION} --tag ghcr.io/principiamentis/fake-smtp-server:latest --output type=image,push=true .
        env:
          IMAGE_VERSION: latest-v1
